// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:delivera/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderProductAdapter());
    registerAdapter(OrderStatusEnumAdapter());
    registerAdapter(OrderTrackingAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ShoppingCartAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderProductAdapter());
    registerAdapter(OrderStatusEnumAdapter());
    registerAdapter(OrderTrackingAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ShoppingCartAdapter());
  }
}
